# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name_city",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название города"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name_warehouse",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название склада"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="app_sales_points.city",
                        verbose_name="Выбор города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Колличество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="app_products.products",
                        verbose_name="Выбор продукта",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stocks",
                        to="app_sales_points.warehouse",
                        verbose_name="Выбор склада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток/Цена",
                "verbose_name_plural": "Остатки/Цены",
            },
        ),
    ]
