# Generated by Django 5.0.6 on 2024-12-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales_points", "0003_alter_edges_content_type"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edges",
            options={"verbose_name": "Маршрут", "verbose_name_plural": "Маршруты"},
        ),
        migrations.AddField(
            model_name="edges",
            name="edges_name",
            field=models.CharField(
                default="test", max_length=100, verbose_name="Название направления"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="edges",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ориентировочная дата доставки"
            ),
        ),
        migrations.AddField(
            model_name="edges",
            name="estimated_delivery_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Количество дней для доставки по маршруту",
                verbose_name="Срок доставки (в днях)",
            ),
        ),
        migrations.AddField(
            model_name="edges",
            name="transportation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Транспортировочные расходы",
            ),
        ),
        migrations.AddIndex(
            model_name="edges",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="app_sales_p_content_de8742_idx",
            ),
        ),
    ]
