# Generated by Django 5.0.6 on 2024-12-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales_points", "0004_alter_edges_options_edges_edges_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edges",
            name="estimated_delivery_date",
        ),
    ]
