# Generated by Django 5.0.6 on 2024-12-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales_points", "0005_remove_edges_estimated_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="edges",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Дата, после которой маршрут становится неактивным.",
                null=True,
                verbose_name="Дата истечения срока действия",
            ),
        ),
        migrations.AddField(
            model_name="edges",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, является ли маршрут активным.",
                verbose_name="Активный статус",
            ),
        ),
    ]
