# Generated by Django 5.0.6 on 2024-12-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales_points", "0006_edges_expiration_date_edges_is_active"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edges",
            name="city_from",
            field=models.ForeignKey(
                help_text="Укажите начальную точку маршрута",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="edges_from",
                to="app_sales_points.city",
                verbose_name="С города",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="city_to",
            field=models.ForeignKey(
                help_text="Укажите конечную точку маршрута",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="edges_to",
                to="app_sales_points.city",
                verbose_name="В город",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="content_type",
            field=models.ForeignKey(
                help_text="Выбирите к чему нужно применить маршрут",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "app_category"), ("model", "category")),
                    models.Q(("app_label", "app_brands"), ("model", "brands")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Объект маршрута",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="edges_name",
            field=models.CharField(
                help_text="Укажите имя для маршрута/направления/ребра. Дожно быть уникальным",
                max_length=100,
                unique=True,
                verbose_name="Название направления",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Дата, до которой (не включительно) маршрут используется системой",
                null=True,
                verbose_name="Дата истечения срока действия",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, является ли маршрут активным. Можно включить/выключить для использования",
                verbose_name="Активный статус",
            ),
        ),
        migrations.AlterField(
            model_name="edges",
            name="object_id",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="edges",
            name="transportation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Возможная наценка на объект маршрута",
                max_digits=10,
                verbose_name="Транспортировочные расходы",
            ),
        ),
        migrations.AddConstraint(
            model_name="edges",
            constraint=models.UniqueConstraint(
                fields=("city_from", "city_to", "object_id"),
                name="unique_edge_constraint",
            ),
        ),
    ]
