# Generated by Django 5.0.6 on 2025-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales_points", "0007_alter_edges_city_from_alter_edges_city_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edges",
            name="expiration_date",
            field=models.DateField(
                help_text="Дата, до которой (не включительно) маршрут используется системой",
                verbose_name="Дата истечения срока действия",
            ),
        ),
    ]
