# Generated by Django 5.0.6 on 2025-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0006_products_app_product_additio_24615d_gin_and_more"),
        ("app_sales_points", "0008_alter_edges_expiration_date"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="edges",
            index=models.Index(
                fields=["city_to"], name="app_sales_p_city_to_2303f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edges",
            index=models.Index(
                fields=["expiration_date"], name="app_sales_p_expirat_5b9a76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edges",
            index=models.Index(
                fields=["is_active"], name="app_sales_p_is_acti_ec5199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product"], name="app_sales_p_product_d0023e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse"], name="app_sales_p_warehou_ef8d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["price"], name="app_sales_p_price_d025bb_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "price"], name="app_sales_p_warehou_ee9fd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["city"], name="app_sales_p_city_id_71c3db_idx"),
        ),
    ]
