# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "title_description",
                    models.CharField(max_length=150, verbose_name="Заголовок описания"),
                ),
            ],
            options={
                "verbose_name": "Описание",
                "verbose_name_plural": "Описания",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DescriptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Это миниатюрное представление изображения описания.",
                        upload_to="descrp_images/%Y/%m/%d/%H/%M/%S/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="ProductDescription",
            fields=[
                (
                    "basedescription_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_descriptions.basedescription",
                    ),
                ),
                (
                    "additional_data_to_desc",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные для перевода описания",
                    ),
                ),
                ("body_description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Описание для продукта",
                "verbose_name_plural": "Описания для продуктов",
            },
            bases=(
                "app_descriptions.basedescription",
                core.mixins.DefaultAdditionalDataMixin,
                models.Model,
            ),
        ),
    ]
