# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_descriptions", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdescription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_products.products",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="descriptionimage",
            name="description",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_descriptions.productdescription",
                verbose_name="Описание",
            ),
        ),
    ]
