# Generated by Django 5.0.6 on 2024-07-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_descriptions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdescription",
            name="product",
        ),
    ]
