# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name_specification",
                    models.CharField(
                        max_length=150, verbose_name="Название характеристики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Название характеристики",
                "verbose_name_plural": "Название характеристик",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ValueSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "value_specification",
                    models.CharField(
                        max_length=150, verbose_name="Значение характеристики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение характеристики",
                "verbose_name_plural": "Значение характеристик",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_specification",
                    models.ForeignKey(
                        help_text="Выберите название для характеристики или создайте новое",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_specifications.namespecifications",
                        verbose_name="Название характеристики",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specifications",
                        to="app_products.products",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "value_specification",
                    models.ForeignKey(
                        help_text="Выберите значение для характеристики или создайте новое",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_specifications.valuespecifications",
                        verbose_name="Значение характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
    ]
