# Generated by Django 5.0.6 on 2025-04-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_specifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specifications",
            options={
                "ordering": ["ind"],
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AddField(
            model_name="specifications",
            name="ind",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядковый номер"
            ),
        ),
    ]
