# Generated by Django 5.0.6 on 2025-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0006_products_app_product_additio_24615d_gin_and_more"),
        ("app_specifications", "0002_alter_specifications_options_specifications_ind"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="specifications",
            index=models.Index(
                fields=["name_specification"], name="app_specifi_name_sp_eb2fe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specifications",
            index=models.Index(
                fields=["value_specification"], name="app_specifi_value_s_6b175b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specifications",
            index=models.Index(
                fields=["product"], name="app_specifi_product_eb74af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specifications",
            index=models.Index(
                fields=["name_specification", "value_specification"],
                name="app_specifi_name_sp_56f81c_idx",
            ),
        ),
    ]
