# Generated by Django 5.0.6 on 2025-05-05 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_specifications",
            "0003_specifications_app_specifi_name_sp_eb2fe1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="namespecifications",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_specification"],
                name="trgm_idx_name_spec",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="valuespecifications",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["value_specification"],
                name="trgm_idx_value_spec",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
