# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name_brand",
                    models.CharField(
                        max_length=150, verbose_name="Наименование бренда"
                    ),
                ),
            ],
            options={
                "verbose_name": "бренд",
                "verbose_name_plural": "бренды",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LogoBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="logo_images/%Y/%m/%d/%H/%M/%S/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_brands.brands",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логотип",
                "verbose_name_plural": "Логотипы",
            },
        ),
    ]
