# Generated by Django 5.0.6 on 2025-01-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brands",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренды"},
        ),
    ]
