# Generated by Django 5.0.6 on 2025-05-05 15:21

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0002_alter_brands_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="brands",
            index=models.Index(
                fields=["name_brand"], name="app_brands__name_br_f70b8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brands",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_brand"],
                name="trgm_idx_name_brand",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
