# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_banner",
                    models.CharField(max_length=150, verbose_name="Название банера"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/%Y/%m/%d/%H/%M/%S/",
                        verbose_name="Изображение банера",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_category.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банер",
                "verbose_name_plural": "Баннеры",
            },
        ),
    ]
