# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_blogs", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="related_product",
            field=models.ManyToManyField(
                blank=True,
                to="app_products.products",
                verbose_name="Сопутствующий товар",
            ),
        ),
        migrations.AddField(
            model_name="blogimage",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_blogs.blog",
                verbose_name="Продукт",
            ),
        ),
    ]
