services:
  web:
    container_name: shop_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8888:8888"
      - "8001:8001"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    entrypoint: [ "/app/entrypoint.sh" ]
    networks:
      - backend

volumes:
  media_volume:
  static_volume:


networks:
  backend:
    external: true
