services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    entrypoint: [ "/app/entrypoint.sh" ]
    networks:
      - backend

volumes:
  media_volume:
  static_volume:


networks:
  backend:
    external: true
