# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID клиента в каспи"
                    ),
                ),
                (
                    "cell_phone",
                    models.CharField(max_length=15, verbose_name="Телефонный номер"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kaspi Клиент",
                "verbose_name_plural": "Kaspi Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID продукта в каспи"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Код артикул",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kaspi Продукт",
                "verbose_name_plural": "Kaspi Продукты",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_value",
                    models.CharField(max_length=255, unique=True, verbose_name="Токен"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Kaspi Токен",
                "verbose_name_plural": "Kaspi Токены",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID ордера"
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код ордера")),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма ордера",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "delivery_cost_for_seller",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Стоимость доставки",
                    ),
                ),
                (
                    "is_kaspi_delivery",
                    models.BooleanField(default=False, verbose_name="Каспи доставка?"),
                ),
                (
                    "delivery_mode",
                    models.CharField(max_length=100, verbose_name="Способ доставки"),
                ),
                (
                    "pre_order",
                    models.BooleanField(default=False, verbose_name="Предзаказ?"),
                ),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="Состояние ордера"),
                ),
                (
                    "approved_by_bank_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата/время принятие банком"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=100, verbose_name="Статус ордера"),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Гео, ширина",
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Гео, долгота",
                    ),
                ),
                (
                    "customer_kaspi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_kaspi.customer",
                        to_field="customer_id",
                        verbose_name="Ссылка на пользователя Каспи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Каспи Заявка",
                "verbose_name_plural": "Каспи Заявки",
            },
        ),
    ]
