# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_kaspi", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prod_in_shop",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_products.products",
                to_field="vendor_code",
                verbose_name="Ссылка на продукт в Магазине",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_in_orders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_kaspi.product",
                to_field="product_id",
                verbose_name="Ссылка на продукт Каспи",
            ),
        ),
    ]
