# Generated by Django 5.0.6 on 2024-07-31 20:07

import app_manager_tags.models
import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "tag_text",
                    models.CharField(max_length=10, verbose_name="Текст тега"),
                ),
                (
                    "font_color",
                    app_manager_tags.models.ColorField(
                        blank=True,
                        default="#FF0000",
                        max_length=7,
                        verbose_name="Цвет шрифта",
                    ),
                ),
                (
                    "fill_color",
                    app_manager_tags.models.ColorField(
                        blank=True,
                        default="#FF0000",
                        max_length=7,
                        verbose_name="Цвет шрифта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
    ]
