# Generated by Django 5.0.6 on 2025-05-05 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_manager_tags", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tag",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tag_text"],
                name="trgm_idx_tag_text",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
