# Generated by Django 5.0.6 on 2025-04-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_brands", "0002_alter_brands_options"),
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_city",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название города"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="ExtProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(max_length=30, verbose_name="Артикул продукта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ext_products",
                        to="app_brands.brands",
                        verbose_name="Бренд продукта",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ext_products",
                        to="app_category.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внешний Продукт",
                "verbose_name_plural": "Внешние Продукты",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name_warehouse",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название склада"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="app_external_products.city",
                        verbose_name="Выбор города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Колличество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="app_external_products.extproduct",
                        verbose_name="Выбор продукта",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stocks",
                        to="app_external_products.warehouse",
                        verbose_name="Выбор склада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток/Цена",
                "verbose_name_plural": "Остатки/Цены",
            },
        ),
    ]
