# Generated by Django 5.0.6 on 2025-04-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_external_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_specification",
                    models.CharField(
                        max_length=150, verbose_name="Название характеристики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Название характеристики",
                "verbose_name_plural": "Название характеристик",
            },
        ),
        migrations.CreateModel(
            name="ValueSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_specification",
                    models.CharField(
                        max_length=150, verbose_name="Значение характеристики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение характеристики",
                "verbose_name_plural": "Значение характеристик",
            },
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_specification",
                    models.ForeignKey(
                        help_text="Выберите название для характеристики или создайте новое",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_external_products.namespecifications",
                        verbose_name="Название характеристики",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specifications",
                        to="app_external_products.extproduct",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "value_specification",
                    models.ForeignKey(
                        help_text="Выберите значение для характеристики или создайте новое",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_external_products.valuespecifications",
                        verbose_name="Значение характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
    ]
