# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_brands", "0001_initial"),
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulatesProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_set",
                    models.CharField(max_length=150, verbose_name="Название сета"),
                ),
                (
                    "activ_set",
                    models.BooleanField(
                        default=False, verbose_name="Активность набора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Популярный продукт",
                "verbose_name_plural": "Популярные продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="product_images/%Y/%m/%d/%H/%M/%S/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="ExternalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=30, verbose_name="Код товара"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("stock", models.IntegerField(blank=True, verbose_name="Остаток")),
                (
                    "warehouse_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Код склада"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_products",
                        to="app_brands.brands",
                        verbose_name="Бренд продукта",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_products",
                        to="app_category.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внешний Продукт",
                "verbose_name_plural": "Внешние Продукты",
            },
        ),
        migrations.CreateModel(
            name="ExternalProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="product_images/%Y/%m/%d/%H/%M/%S/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "external_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.externalproduct",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Артикул продукта"
                    ),
                ),
                (
                    "name_product",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_brands.brands",
                        verbose_name="бренд продукта",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="app_category.category",
                        verbose_name="Категория продукта",
                    ),
                ),
                (
                    "configuration",
                    models.ManyToManyField(
                        blank=True,
                        to="app_products.products",
                        verbose_name="Комплектации",
                    ),
                ),
                (
                    "present",
                    models.ManyToManyField(
                        blank=True, to="app_products.products", verbose_name="В подарок"
                    ),
                ),
                (
                    "related_product",
                    models.ManyToManyField(
                        blank=True,
                        to="app_products.products",
                        verbose_name="Сопутствующий товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
    ]
