# Generated by Django 5.0.6 on 2024-07-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_manager_tags", "0001_initial"),
        ("app_products", "0001_initial"),
        ("app_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="app_services.service", verbose_name="Услуги к продукту"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="tag_prod",
            field=models.ManyToManyField(
                blank=True, to="app_manager_tags.tag", verbose_name="Теги продукта"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_products.products",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="populatesproducts",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                to="app_products.products",
                verbose_name="Список популярных продуктов",
            ),
        ),
    ]
