# Generated by Django 5.0.6 on 2024-07-31 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0001_initial"),
        ("app_descriptions", "0003_remove_productdescription_product"),
        ("app_products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_descriptions.productdescription",
                verbose_name="Описание продукта",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_brands.brands",
                verbose_name="Бренд продукта",
            ),
        ),
    ]
