# Generated by Django 5.0.6 on 2025-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_products_description_alter_products_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["ind"],
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AddField(
            model_name="productimage",
            name="ind",
            field=models.PositiveIntegerField(
                default=0,
                help_text="1 - это обложка (пример)",
                verbose_name="Порядковый номер",
            ),
        ),
    ]
