# Generated by Django 5.0.6 on 2025-05-05 10:43

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0002_alter_brands_options"),
        ("app_category", "0001_initial"),
        ("app_descriptions", "0003_remove_productdescription_product"),
        ("app_manager_tags", "0001_initial"),
        ("app_products", "0004_alter_productimage_options_productimage_ind"),
        ("app_services", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="products",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_product"],
                name="trgm_idx_name_product",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vendor_code"],
                name="trgm_idx_vendor_code",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
