# Generated by Django 5.0.6 on 2025-05-05 15:21

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0003_brands_app_brands__name_br_f70b8b_idx_and_more"),
        ("app_category", "0002_category_app_categor_slug_4b2c6d_idx_and_more"),
        ("app_descriptions", "0003_remove_productdescription_product"),
        ("app_manager_tags", "0001_initial"),
        ("app_products", "0005_products_trgm_idx_name_product_and_more"),
        ("app_services", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="products",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["additional_data"], name="app_product_additio_24615d_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(
                fields=["category"], name="app_product_categor_b14c0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(fields=["brand"], name="app_product_brand_i_d9c3ee_idx"),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(fields=["slug"], name="app_product_slug_06ec32_idx"),
        ),
    ]
