# Generated by Django 5.0.6 on 2025-05-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0006_products_app_product_additio_24615d_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="show_it",
            field=models.BooleanField(
                default=True, verbose_name="Показывать этот товар?"
            ),
        ),
    ]
