# Generated by Django 5.0.6 on 2025-05-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0007_products_show_it"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="populatesproducts",
            name="products",
        ),
        migrations.CreateModel(
            name="ProductSetProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_value", models.IntegerField()),
                (
                    "populatesproducts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.populatesproducts",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.products",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_value"],
            },
        ),
    ]
