# Generated by Django 5.0.6 on 2025-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0008_remove_populatesproducts_products_productsetproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="populatesproducts",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="app_products.ProductSetProduct",
                to="app_products.products",
                verbose_name="Список популярных продуктов",
            ),
        ),
    ]
