# Generated by Django 5.0.6 on 2025-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0009_populatesproducts_products"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Добавить новое поле для tsvector
            ALTER TABLE app_products_products
            ADD COLUMN IF NOT EXISTS search_vector tsvector;

            -- Создать индекс GIN по этому полю
            CREATE INDEX IF NOT EXISTS product_search_vector_idx
            ON app_products_products
            USING GIN (search_vector);

            -- Создать функцию обновления search_vector
            CREATE OR REPLACE FUNCTION update_product_search_vector() RETURNS trigger AS $$
            BEGIN
              NEW.search_vector :=
                setweight(to_tsvector('russian', coalesce(NEW.name_product, '')), 'A') ||
                setweight(to_tsvector('russian', coalesce(NEW.additional_data::text, '')), 'B') ||
                setweight(to_tsvector('russian', coalesce(NEW.vendor_code, '')), 'C');
              RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            -- Добавить BEFORE INSERT/UPDATE триггер
            DROP TRIGGER IF EXISTS tsvectorupdate_products ON app_products_products;

            CREATE TRIGGER tsvectorupdate_products
            BEFORE INSERT OR UPDATE
            ON app_products_products
            FOR EACH ROW EXECUTE FUNCTION update_product_search_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS tsvectorupdate_products ON app_products_products;
            DROP FUNCTION IF EXISTS update_product_search_vector();
            DROP INDEX IF EXISTS product_search_vector_idx;
            ALTER TABLE app_products_products DROP COLUMN IF EXISTS search_vector;
            """,
        )
    ]
