# Generated by Django 5.0.6 on 2024-07-31 20:07

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название скидки"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание скидки"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность скидки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала действия"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания действия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка на продук",
                "verbose_name_plural": "Скидка на продукы",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CategoryDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название скидки"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание скидки"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность скидки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала действия"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания действия"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="app_category.category", verbose_name="Категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка на категорию",
                "verbose_name_plural": "Скидка на категории",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
    ]
