# Generated by Django 5.0.6 on 2024-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_discounts", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscount",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="app_products.products", verbose_name="Продукты"
            ),
        ),
    ]
