# Generated by Django 5.0.6 on 2025-01-04 21:45

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0002_alter_brands_options"),
        ("app_discounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=core.mixins.DefaultAdditionalDataMixin.default_additional_data,
                        help_text="Данные поля предназначены для перевода на другие языки.<br>\n                        Можно добавить сколько угодно переводов.",
                        null=True,
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название скидки"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание скидки"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность скидки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала действия"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания действия"
                    ),
                ),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, to="app_brands.brands", verbose_name="Бренд"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка на бренд",
                "verbose_name_plural": "Скидка на бренды",
            },
            bases=(core.mixins.DefaultAdditionalDataMixin, models.Model),
        ),
    ]
