# Generated by Django 5.0.6 on 2025-01-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_brands", "0002_alter_brands_options"),
        ("app_category", "0001_initial"),
        ("app_discounts", "0003_branddiscount"),
        ("app_products", "0003_products_description_alter_products_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branddiscount",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                related_name="brand_discounts",
                to="app_brands.brands",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="categorydiscount",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="category_discounts",
                to="app_category.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_discounts",
                to="app_products.products",
                verbose_name="Продукты",
            ),
        ),
    ]
