# Generated by Django 5.0.6 on 2024-12-09 21:47

import app_orders.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baskets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("uuid_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                (
                    "completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "checkout_stage",
                    models.CharField(
                        choices=[
                            ("CREATED", "created"),
                            ("PROCESSING", "processing"),
                            ("COMPLETED", "completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("basket_items", models.JSONField(blank=True, default=list, null=True)),
                ("gift_items", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "db_table": "baskets",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_full_name", models.CharField(max_length=255)),
                ("user_id", models.UUIDField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=10
                    ),
                ),
                (
                    "account_number",
                    models.IntegerField(
                        default=app_orders.models.generate_account_number, unique=True
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("shipping_city", models.CharField(max_length=255)),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        default="delivery",
                        max_length=20,
                    ),
                ),
                (
                    "manager_executive",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uuid_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_orders.baskets",
                        to_field="uuid_id",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
