# Generated by Django 5.0.6 on 2024-12-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baskets",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"managed": False},
        ),
    ]
