# Generated by Django 5.0.6 on 2025-05-05 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_category", "0002_category_app_categor_slug_4b2c6d_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_category"],
                name="trgm_idx_name_category",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
