# Generated by Django 5.0.6 on 2024-07-31 20:07

import app_reviews.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[app_reviews.models.valid],
                        verbose_name="Оценка/Рейтинг",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        max_length=2000, unique=True, verbose_name="Отзыв"
                    ),
                ),
                (
                    "moderation",
                    models.BooleanField(default=False, verbose_name="Модерация"),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID пользователя"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв/Рейтинг",
                "verbose_name_plural": "Отзывы/Рейтинги",
            },
        ),
    ]
