# Generated by Django 5.0.6 on 2025-01-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_products_description_alter_products_brand"),
        ("app_reviews", "0002_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="app_products.products",
                verbose_name="Продукт",
            ),
        ),
    ]
