# Generated by Django 5.0.6 on 2025-03-26 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reviews", "0003_alter_review_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                verbose_name="ID пользователя",
            ),
        ),
    ]
