# Generated by Django 5.0.6 on 2025-03-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_reviews", "0004_review_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user_id",
        ),
    ]
